Update build_spec.yaml

diff --git a/build_spec.yaml b/build_spec.yaml
--- a/build_spec.yaml
+++ b/build_spec.yaml
@@ -9,13 +9,15 @@ phases:
       - echo "Setting up environment variables..."
       - export IMAGE_NAME=todolistapp-springboot
       - export IMAGE_VERSION=0.1
-      - if [ -z "$DOCKER_REGISTRY" ]; then
-          echo "DOCKER_REGISTRY not set. Will get it with state_get";
-          export DOCKER_REGISTRY=$(state_get DOCKER_REGISTRY);
+      - |
+        if [ -z "$DOCKER_REGISTRY" ]; then
+          echo "DOCKER_REGISTRY not set. Will get it with state_get"
+          export DOCKER_REGISTRY=$(state_get DOCKER_REGISTRY)
         fi
-      - if [ -z "$DOCKER_REGISTRY" ]; then
-          echo "Error: DOCKER_REGISTRY env variable needs to be set!";
-          exit 1;
+      - |
+        if [ -z "$DOCKER_REGISTRY" ]; then
+          echo "Error: DOCKER_REGISTRY env variable needs to be set!"
+          exit 1
         fi
       - export IMAGE=${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}
   build:
@@ -28,9 +30,10 @@ phases:
     commands:
       - echo "Pushing Docker image to registry..."
       - docker push $IMAGE
-      - if [ $? -eq 0 ]; then
-          echo "Removing local Docker image...";
-          docker rmi "$IMAGE";
+      - |
+        if [ $? -eq 0 ]; then
+          echo "Removing local Docker image..."
+          docker rmi "$IMAGE"
         fi
 artifacts:
   files:
