Update build_spec.yaml

diff --git a/MtdrSpring/backend/build_spec.yaml b/MtdrSpring/backend/build_spec.yaml
--- a/MtdrSpring/backend/build_spec.yaml
+++ b/MtdrSpring/backend/build_spec.yaml
@@ -1,27 +1,61 @@
-version: 0.1 
+version: 0.1
 component: build
-timeoutInSeconds: 100
+timeoutInSeconds: 10000
 shell: bash
+failImmediatelyOnError: true
 
 env:
   variables:
+    IMAGE_NAME: "todolistapp-springboot"
+    IMAGE_VERSION: "0.1"
     DOCKER_REGISTRY: "qro.ocir.io/axs2pxpd649r"
+    JAVA_HOME: "/usr/lib64/graalvm/graalvm22-ee-java17"
     DOCKER_USERNAME: "axs2pxpd649r/prm-123@hotmail.com"
     DOCKER_PASSWORD: "7srs5zmwRFMBj]>VBrnL"
-    JAVA_HOME: /usr/lib64/graalvm/graalvm22-ee-java17
-
   exportedVariables:
-    - BuildServiceDemoVersion
+    - IMAGE
 
 steps:
   - type: Command
-    name: "Install GraalVM Enterprise 22.x Native Image for Java17"
-    command: yum -y install graalvm22-ee-17-native-image
+    name: Set Environment Variables
+    shell: bash
+    timeoutInSeconds: 300
+    command: |
+      if [ -z "$DOCKER_REGISTRY" ]; then
+        echo "DOCKER_REGISTRY not set. Exiting..."
+        exit 1
+      fi
+      export IMAGE=${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}
+      echo "Environment variables set: IMAGE=${IMAGE}"
+      export PATH=$JAVA_HOME/bin:$PATH
+      echo "PATH set to: $PATH"
 
   - type: Command
-    name: "Set PATH Variable"
-    command: export PATH=$JAVA_HOME/bin:$PATH
-
+    name: Install GraalVM Enterprise 22.x Native Image for Java17
+    shell: bash
+    timeoutInSeconds: 600
+    command: |
+      echo "Installing GraalVM Enterprise..."
+      yum -y install graalvm22-ee-17-native-image
+      if [ $? -ne 0 ]; then
+        echo "GraalVM installation failed!"
+        exit 1
+      fi
+      echo "GraalVM installation succeeded."
+  
+  - type: Command
+    name: Login to OCI Docker Registry
+    shell: bash
+    timeoutInSeconds: 300
+    command: |
+      echo "Logging in to OCI Docker Registry..."
+      echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin
+      if [ $? -ne 0 ]; then
+        echo "Docker login failed!"
+        exit 1
+      fi
+      echo "Docker login succeeded."
+  
   - type: Command
     name: Build Application
     shell: bash
@@ -37,36 +71,27 @@ steps:
       echo "Maven build succeeded."
 
   - type: Command
-    name: check
-    command: ls -la MtdrSpring/backend/target/
-
-  - type: Command
-    name: Login to OCI Docker Registry
+    name: Build Docker Image
     shell: bash
-    timeoutInSeconds: 300
+    timeoutInSeconds: 600
     command: |
-      echo "Logging in to OCI Docker Registry..."
-      echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin
+      echo "Building Docker image..."
+      docker build -f MtdrSpring/backend/Dockerfile -t $IMAGE MtdrSpring/backend --platform=linux/arm64
       if [ $? -ne 0 ]; then
-        echo "Docker login failed!"
+        echo "Docker build failed!"
         exit 1
       fi
-      echo "Docker login succeeded."
+      echo "Docker build succeeded."
 
   - type: Command
-    name: Dockerize
+    name: Push Docker Image
+    shell: bash
+    timeoutInSeconds: 600
     command: |
-      BuildServiceDemoVersion=`echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7`
-      echo $BuildServiceDemoVersion
-      docker build -f MtdrSpring/backend/Dockerfile -t artifact_docker1 MtdrSpring/backend --platform=linux/arm64
-
-  - type: Command
-    name: "List Docker Images"
-    command: docker images
-
-outputArtifacts:  
-  - name: artifact_docker
-    type: DOCKER_IMAGE
-    location: artifact_docker1
-
-
+      echo "Pushing Docker image to registry..."
+      docker push $IMAGE
+      if [ $? -ne 0 ]; then
+        echo "Docker push failed!"
+        exit 1
+      fi
+      echo "Docker push succeeded."
