Update build_spec.yaml

diff --git a/MtdrSpring/backend/build_spec.yaml b/MtdrSpring/backend/build_spec.yaml
--- a/MtdrSpring/backend/build_spec.yaml
+++ b/MtdrSpring/backend/build_spec.yaml
@@ -10,6 +10,8 @@ env:
     IMAGE_VERSION: "0.1"
     DOCKER_REGISTRY: "mx-queretaro-1.ocir.io/axs2pxpd649r/reacttodo/rkihw"
     JAVA_HOME: "/usr/lib64/graalvm/graalvm22-ee-java17"
+    DOCKER_USERNAME: "axs2pxpd649r/prm-123@hotmail.com"
+    DOCKER_PASSWORD: "7srs5zmwRFMBj]>VBrnL"
   exportedVariables:
     - IMAGE
 
@@ -40,7 +42,18 @@ steps:
         exit 1
       fi
       echo "GraalVM installation succeeded."
-
+  - type: Command
+      name: Login to OCI Docker Registry
+      shell: bash
+      timeoutInSeconds: 300
+      command: |
+        echo "Logging in to OCI Docker Registry..."
+        echo $DOCKER_PASSWORD | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin
+        if [ $? -ne 0 ]; then
+          echo "Docker login failed!"
+          exit 1
+        fi
+        echo "Docker login succeeded."
   - type: Command
     name: Build Application
     shell: bash
